# Deontology

AC: right action is the one that produces the most good.

Who's good?

Objective v. Subjective Consequentialism

> The view that whenever one faces a choice of actions, one should attmpt to determinie which act of those available would most promote the good, and should then try to act accordingly. One is behaving as subjective consequentialism requires . . . to the extent that one uses and follolws a distinctively consequentialist mode of decision making, consciously aiming at the overall good and conscientiously using the best available information with the greatest possible rigor. [Railton 1988, p. 113]

D: Not producing the most good, rather . . .

## Some Basic Features

### Constraints

What are some ways that we are contrained by deontological principles?

* Must not harm, lie, kill, torture under any circumstances.

Therefore, we are constrained in what we can do.

### Duties of Special Relationships

Sometimes we have special committments to others.

* Child
* Parent
* Spouse
* Friend

Our actions which respect to these relationships are constrained. Even if we could maximize the good, for instance, play video games instead of tucking our children into bed.


### Options

### Agent-Relative and Agent-Neutral Theories

## Non-Deontological Theories

### Consequentialisms

### Nonconsequentialist Nondeontological Theories

## Rossian Deontology

## Particularism

## Alternative Foundations for Deontology

### Kant

### Scanlon

## Defending Deontology

### Special Relationships

### Options

### Constraints

### Virtue Ethics
